// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoduthqkxhphvlldxyjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZHV0aHFreGhwaHZsbGR4eWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwODU0ODIsImV4cCI6MjA5MTY2MTQ4Mn0.R3wnKBwOt1WfTJVfFr3sPWydUFtE9cp2PohjEy4R6H4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});